# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anapen 2
email: a.toussaint@bioprojet.de
description: Anapen 2 wird zur Notfallbehandlung von Symptomen des anaphylaktischen Schocks angewendet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: theme-sb-anapen2

defaults:
  - scope:
      path: index.html
    values:
      layout: default
      style_id: home
  - scope:
      path: infocenter.md
    values:
      layout: page
      style_id: infocenter
  - scope:
      path: anwendung.md
    values:
      layout: page
      style_id: anwendung
  - scope:
      path: was-ist-neu.html
    values:
      layout: page
      style_id: wasistneu
  - scope:
      path: kontakt.html
    values:
      layout: page
      style_id: kontakt
  - scope:
      path: impressum.html
    values:
      layout: page
      style_id: impressum
  - scope:
      path: danke.html
    values:
      layout: page
      style_id: danke
  - scope:
      path: datenschutz.html
    values:
      layout: page
      style_id: datenschutz
  - scope:
      path: intern.html
    values:
      layout: page
      style_id: intern

assets:
  compress:
    css: true
    js: true
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

plugins:
  - theme-sb-anapen2
  - jekyll-assets
  - jekyll-sitemap
  - mini_magick
  - autoprefixer-rails
  - uglifier
